# Generated by Django 3.1.2 on 2021-01-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('total_publication', models.IntegerField()),
                ('average_reader_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('growth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quick_search_data', models.BooleanField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
