# Generated by Django 3.1.3 on 2021-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_keyword', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='score',
            field=models.FloatField(),
        ),
    ]
