# Generated by Django 3.1.2 on 2021-01-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_keyword', '0003_auto_20210116_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='average_reader_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='growth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='total_publication',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyword',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
