# Generated by Django 3.1.2 on 2021-01-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory', '0001_initial'),
        ('search_keyword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory_combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('subcategory_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_1', to='subcategory.subcategory')),
                ('subcategory_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_2', to='subcategory.subcategory')),
            ],
            options={
                'unique_together': {('subcategory_1', 'subcategory_2')},
            },
        ),
        migrations.CreateModel(
            name='keyword_combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_publication', models.IntegerField()),
                ('average_reader_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('growth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quick_search_data', models.BooleanField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('keyword_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_1', to='search_keyword.keyword')),
                ('keyword_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_2', to='search_keyword.keyword')),
            ],
            options={
                'unique_together': {('keyword_1', 'keyword_2')},
            },
        ),
    ]
