# Generated by Django 3.1.3 on 2021-01-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Combination',
        ),
    ]
