# Generated by Django 3.1.2 on 2021-01-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_keyword', '0001_initial'),
        ('combinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword_combination',
            name='keyword_1',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_1', to='search_keyword.keyword'),
        ),
        migrations.AlterField(
            model_name='keyword_combination',
            name='keyword_2',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_2', to='search_keyword.keyword'),
        ),
    ]
