# Generated by Django 3.1.2 on 2021-01-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory', '0001_initial'),
        ('search_keyword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('reader_count', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
                ('year_published', models.IntegerField()),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paper_subcategory_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_of_subcategories', to='paper.paper')),
                ('paper_subcategory_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_subcategory_1', to='subcategory.subcategory')),
                ('paper_subcategory_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_subcategory_2', to='subcategory.subcategory')),
            ],
            options={
                'unique_together': {('paper_subcategory_1', 'paper_subcategory_2', 'paper')},
            },
        ),
        migrations.CreateModel(
            name='paper_keyword_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_of_keywords', to='paper.paper')),
                ('paper_keyword_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_keyword_1', to='search_keyword.keyword')),
                ('paper_keyword_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_keyword_2', to='search_keyword.keyword')),
            ],
            options={
                'unique_together': {('paper_keyword_1', 'paper_keyword_2', 'paper')},
            },
        ),
    ]
